### ISSUE TITLE
add upload for assets like images, videos and pdf files

### ISSUE THREAD

**Issue by erileg** [sne11ius/egghead.space#14]

**Comment by sne11ius** [comment]
Ans videos and images

**Comment by sne11ius** [comment]
And disallow external images in markdown.

**Comment by sne11ius** [comment]
uppy.io seems to be the king. Just 2 easy steps:
1. Implement firebase storage backend for uppy
2. Implement vuetify frontend for uppy
3. ...
4. much win

**Comment by sne11ius** [comment]
PDFs are not good imo, since they cannot be embedded in the page.
Video is more work than I'm willing to put in right now. I think we should do this in a later version.

**Comment by sne11ius** [comment]
The pdf stuff might actually work:
https://github.com/arkokoley/pdfvuer
