### ISSUE TITLE
Liking a sketch is refused with 403

### ISSUE THREAD

**Issue by erileg** [sne11ius/egghead.space#37]

**Comment by sne11ius** [comment]
Hehe :D
I started to implement more sophisticated firestore.rules.
Its a mess: examples are rare to find, documentation is somewhat shallow and there is zero possibility to debug or see whats going on (see https://groups.google.com/forum/#!topic/google-cloud-firestore-discuss/34IxMQHewdY).

I will revert the rules to "all read, authenticated write" and we can implement better rules once the features have stabilized a bit more.

see #38
